services:
  # 1. The Express Backend Web Service
  - type: web
    name: capstone-backend
    runtime: node
    repo: https://github.com/agonzalez-gomez/capstone-project
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5050"
      - key: ATLAS_URI
        sync: false

  # 2. The React Frontend Web Service
  - type: web
    name: capstone-frontend
    runtime: node
    repo: https://github.com/agonzalez-gomez/capstone-project
    rootDir: client
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://capstone-backend.onrender.com
